package triage

import (
	"strings"

	"github.com/Pnarayan-3/Issue-Triage-Agent/internal/ai"
)

func BuildLabels(result *ai.TriageResult) []string {

	labels := []string{
		"type:" + strings.ToLower(result.Type),
		"priority:" + strings.ToLower(result.Priority),
		"severity:" + strings.ToLower(result.Severity),
		"component:" + strings.ToLower(result.Component),
		"team:" + strings.ToLower(result.Team),
	}

	// Add contextual labels generated by AI.
	for _, label := range result.Labels {

		label = strings.TrimSpace(strings.ToLower(label))

		if label == "" {
			continue
		}

		if !contains(labels, label) {
			labels = append(labels, label)
		}
	}

	return labels
}

func contains(labels []string, target string) bool {

	for _, label := range labels {
		if label == target {
			return true
		}
	}

	return false
}